version: '3'
services:
  khan-client:
    container_name: khan-client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://api.kkhan.co.kr}
    ports:
      - "8026:80"
